#ifndef ERROR_CODES_H
#define ERROR_CODES_H
#define ERR_FILE_NOT_FOUND 100
#define ERR_FILE_IN_USE 102
#define ERR_DIR_NOT_FOUND 103
#define ERR_PATH_NOT_FOUND 106
#define ERR_NOT_A_FILE 107
#define ERR_SRC_FILE_NOT_FOUND 110
#define ERR_SRC_DIR_NOT_FOUND 111
#define ERR_DEST_DIR_NOT_FOUND 112
#define ERR_NOT_AUDIO_FILE 113
#endif 
